
name: Build APK Flutter 1.22.6

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Android cmdline-tools
        run: |
          echo "y" | sudo ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --sdk_root=${ANDROID_HOME} "cmdline-tools;10.0"

      - name: Install NDK 21e
        run: |
          echo "y" | sudo ${ANDROID_HOME}/cmdline-tools/10.0/bin/sdkmanager --sdk_root=${ANDROID_HOME} "ndk;21.4.7075529"

      - name: Set NDK path
        run: echo "ndk.dir=${ANDROID_HOME}/ndk/21.4.7075529" >> android/local.properties

      - name: Install Flutter 1.22.6
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "1.22.6"

      - name: Get dependencies
        run: flutter pub get

      - name: Set up Java 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Build APK (Android 4.x)
        run: flutter build apk --target-platform android-arm

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
